<?php

$competencias = [
    ['nome' => 'Adaptabilidade e Flexibilidade', 'descricao' => 'Lida com situações novas ou cenários adversos, adaptando-se de forma ágil e eficaz aos desafios enfrentados e aos contextos de mudança organizacional.
    ', 'posto_id' => 1],
    ['nome' => 'Foco no usuário/nas pessoas', 'descricao'=> 'Concentra seus esforços e sua atenção na identifi¬cação, compreensão e resposta às necessidades apresentadas pelas pessoas, de forma célere e acessível.','posto_id' => 1],
    ['nome' => 'Relacionamento interpessoal', 'descricao'=> 'Relaciona-se de forma eficaz, adaptando seu comportamento a culturas e públicos diferentes, estabelecendo relacionamentos construtivos e desenvolvendo trocas produtivas e eficientes.', 'posto_id' => 1],
    ['nome' => 'Engajamento e Comprometimento com Resultados', 'descricao'=> 'É engajado com os objetivos e valores da organização e comprometido com o alcance dos resultados, tarefas e atividades, de forma responsável e proativa.', 'posto_id' => 1],
    ['nome' => 'Comunicação', 'descricao'=> 'Comunica-se de forma eficiente e eficaz, interagindo de maneira apropriada e empática com diversos públicos.', 'posto_id' => 1],
    ['nome' => 'Gestão de Equipes', 'descricao'=> 'É capaz de formar, liderar, motivar e desenvolver sua equipe de trabalho, favorecendo a colaboração, a comunicação eficaz e a solução de conflitos de maneira construtiva de forma a promover um ambiente de trabalho harmonioso e produtivo.', 'posto_id' => 2],
    ['nome' => 'Gestão por Resultados', 'descricao'=> 'É capaz de definir, planejar, executar e monitorar atividades e projetos com foco no alcance de objetivos e metas estabelecidos, otimizando recursos e maximizando a eficiência. Utiliza indicadores de desempenho para medir o progresso, toma decisões baseadas em dados e ajusta estratégias conforme necessário para garantir o sucesso organizacional.', 'posto_id' => 2],
    ['nome' => 'Gestão de Mudanças e Inovação', 'descricao'=> 'É capaz de identificar oportunidades de mudança e inovação, liderar processos de transformação organizacional e promover uma cultura que encoraje a criatividade, a adaptação e o aprendizado contínuo. Gerencia resistências, comunica de forma eficaz e envolver a equipe no processo de mudança, garantindo o sucesso da implementação de novas ideias e práticas inovadoras.', 'posto_id' => 2],
    ['nome' => 'Gestão Participativa', 'descricao'=> 'Atua de forma a incluir e engajar os membros da equipe na tomada de decisões, planejamento e execução das atividades, promovendo um ambiente de trabalho colaborativo e democrático, valorizando a opinião e as ideias dos membros da equipe e utilizando a diversidade de perspectivas para melhorar os processos e resultados organizacionais.', 'posto_id' => 2],
    ['nome' => 'Autoliderança', 'descricao'=> 'Gerenciar e lidera a si mesmo de forma eficaz, demonstrando autodisciplina, autoconsciência e autorresponsabilidade. É capaz de estabelecer metas claras, manter o foco, lidar com desafios e adversidades de forma construtiva e tomar decisões apostodas com seus valores e objetivos pessoais e profissionais.', 'posto_id' => 2],
    ['nome' => 'Disciplina', 'posto_id' => 3,'descricao' => 'Segue normas, procedimentos e orientações da organização, respeitando prazos, regras e hierarquias, cumprindo os seus deveres e mantendo-se dentro dos padrões éticos e profissionais estabelecidos.'],
    ['nome' => 'Responsabilidade', 'posto_id' => 3, 'descricao' => 'Assume compromisso com suas atividades, sendo capaz de cumprir prazos e padrões de qualidade nas tarefas atribuídas. Demonstra confiabilidade e cuidado com informações sigilosas.'],
    ['nome' => 'Capacidade de Iniciativa', 'posto_id' => 3, 'descricao' => 'Antecipa-se a problemas e sugere soluções, sem a necessidade de ordens ou supervisão constante. Demonstra disposição para identificar oportunidades de melhoria e agir para implementar mudanças positivas no ambiente de trabalho.'],
    ['nome' => 'Produtividade', 'posto_id' => 3, 'descricao' => 'Gera resultados consistentes e proporcionais à sua complexidade. É capaz de realizar entregas de qualidade no tempo previsto, otimizando os recursos disponíveis. Demonstra eficiência na execução de suas atividades.'],
    ['nome' => 'Assiduidade', 'posto_id' => 3, 'descricao' => 'Cumpre a jornada de trabalho na forma estabelecida pelo Tribunal, realizando as atividades pertinentes ao trabalho e mantendo-se à disposição da unidade. Comunica à chefia imediata, em tempo hábil, sobre a ocorrência de situações excepcionais que impactem na sua jornada, negociando prazos e entregas.'],
    ['nome' => 'Execução no processo do trabalho', 'posto_id' => 4],
    ['nome' => 'Formação inicial de servidores da área jurídica', 'posto_id' => 4],
    ['nome' => 'Gabinete eletrônico', 'posto_id' => 4],
    ['nome' => 'Inovações em direito processual', 'posto_id' => 4],
    ['nome' => 'Juízo de admissibilidade em recurso extraordinário', 'posto_id' => 4],
    ['nome' => 'Julgamento com perspectiva de diversidade e inclusão', 'posto_id' => 4],
    ['nome' => 'Letramento racial e de gênero aplicados aos temas processuais', 'posto_id' => 4],
    ['nome' => 'Linguagem jurídica e português jurídico', 'posto_id' => 4],
    ['nome' => 'Lógica jurídica', 'posto_id' => 4],
    ['nome' => 'Mediação e Conciliação', 'posto_id' => 4],
    ['nome' => 'Normas regulamentadoras do Ministério do Trabalho', 'posto_id' => 4],
    ['nome' => 'Nulidades processuais', 'posto_id' => 4],
    ['nome' => 'Pesquisa jurisprudencial', 'posto_id' => 4],
    ['nome' => 'Plenário eletrônico', 'posto_id' => 4],
    ['nome' => 'Precedentes vinculantes e sistemática de elaboração de súmulas ou OJs', 'posto_id' => 4],
    ['nome' => 'Prescrição trabalhista', 'posto_id' => 4],
    ['nome' => 'Processo judicial eletrônico', 'posto_id' => 4],
    ['nome' => 'Reforma trabalhista', 'posto_id' => 4],
    ['nome' => 'Regimento Interno', 'posto_id' => 4],
    ['nome' => 'Responsabilidade civil', 'posto_id' => 4],
    ['nome' => 'Secretaria eletrônica', 'posto_id' => 4],
    ['nome' => 'Seguro garantia', 'posto_id' => 4],
    ['nome' => 'Sistema Hermes', 'posto_id' => 4],
    ['nome' => 'Súmulas processuais aplicáveis aos recursos', 'posto_id' => 4],
    ['nome' => 'Temas de repercussão geral', 'posto_id' => 4],
    ['nome' => 'Teoria Geral de Precedentes', 'posto_id' => 4],
    ['nome' => 'Tutelas de urgência e de evidência', 'posto_id' => 4],
    ['nome' => 'Aposentadoria e pensão', 'posto_id' => 5],
    ['nome' => 'Cálculo de aposentadorias e pensões', 'posto_id' => 5],
    ['nome' => 'Conformidade em gestão de pessoas', 'posto_id' => 5],
    ['nome' => 'Direito administrativo aplicado a pessoal', 'posto_id' => 5],
    ['nome' => 'Direito processual civil - Fazenda pública - aplicado a pessoal', 'posto_id' => 5],
    ['nome' => 'Folha de pagamento do TST', 'posto_id' => 5],
    ['nome' => 'Lei 8.112/90 - atualizações e jurisprudências', 'posto_id' => 5],
    ['nome' => 'Lei geral de proteção de dados aplicada à gestão de pessoas', 'posto_id' => 5],
    ['nome' => 'Análise de dados de pessoal', 'posto_id' => 6],
    ['nome' => 'Avaliação do tipo consultoria', 'posto_id' => 6],
    ['nome' => 'Auditoria baseada em riscos', 'posto_id' => 6],
    ['nome' => 'Auditoria interna governamental', 'posto_id' => 6],
    ['nome' => 'Contabilidade Pública com foco em auditoria', 'posto_id' => 6],
    ['nome' => 'Modelo de capacidade de auditoria interna - IA-CM', 'posto_id' => 6],
    ['nome' => 'Normas e orientações sobre práticas de auditoria - IPPF', 'posto_id' => 6],
    ['nome' => 'Competências comunicacionais', 'posto_id' => 7],
    ['nome' => 'Copywriting', 'posto_id' => 7],
    ['nome' => 'E-mail marketing, marketing de conteúdo, branding e growth marketing', 'posto_id' => 7],
    ['nome' => 'Endomarketing e redação criativa', 'posto_id' => 7],
    ['nome' => 'Ferramentas de edição de imagem', 'posto_id' => 7],
    ['nome' => 'Mídias sociais', 'posto_id' => 7],
    ['nome' => 'Redação publicitária', 'posto_id' => 7],
    ['nome' => 'Análise de demonstrações contábeis', 'posto_id' => 8],
    ['nome' => 'Auditoria contábil via Sistema integrado de administração financeira', 'posto_id' => 8],
    ['nome' => 'do Governo Federal - SIAFI', 'posto_id' => 8],
    ['nome' => 'Contabilidade geral', 'posto_id' => 8],
    ['nome' => 'Contabilidade pública', 'posto_id' => 8],
    ['nome' => 'Gestão de custos no serviço público', 'posto_id' => 8],
    ['nome' => 'Regularizações Contábeis', 'posto_id' => 8],
    ['nome' => 'Sistema de Informações de Custos', 'posto_id' => 8],
    ['nome' => 'Cálculos trabalhistas em contratos de terceirização', 'posto_id' => 9],
    ['nome' => 'Contratação direta - inexigibilidade e dispensa', 'posto_id' => 9],
    ['nome' => 'Ética, Integridade e Responsabilização em Contratações', 'posto_id' => 9],
    ['nome' => 'Execução contratual - práticas de gestão e controle', 'posto_id' => 9],
    ['nome' => 'Fiscalização de contratos', 'posto_id' => 9],
    ['nome' => 'Fiscalização de contratos de terceirização', 'posto_id' => 9],
    ['nome' => 'Gestão de riscos com foco em contratações', 'posto_id' => 9],
    ['nome' => 'Licitações e contratos', 'posto_id' => 9],
    ['nome' => 'Licitações sustentáveis', 'posto_id' => 9],
    ['nome' => 'Nova lei de licitações e contratos', 'posto_id' => 9],
    ['nome' => 'Planejamento de contratações - estudo técnico preliminar, termo de referência e edital', 'posto_id' => 9],
    ['nome' => 'Planilha de custos e formação de preços em contratos de terceirização', 'posto_id' => 9],
    ['nome' => 'Ambientes virtuais de aprendizagem', 'posto_id' => 10],
    ['nome' => 'Cargos e carreiras', 'posto_id' => 10],
    ['nome' => 'Consultoria interna em recursos humanos', 'posto_id' => 10],
    ['nome' => 'Cultura e engajamento', 'posto_id' => 10],
    ['nome' => 'Diferenças geracionais', 'posto_id' => 10],
    ['nome' => 'Dimensionamento da força do trabalho', 'posto_id' => 10],
    ['nome' => 'Experiência do colaborador', 'posto_id' => 10],
    ['nome' => 'Formação de formadores', 'posto_id' => 10],
    ['nome' => 'Formação de liderança e sucessão', 'posto_id' => 10],
    ['nome' => 'Gestão de treinamento', 'posto_id' => 10],
    ['nome' => 'Inteligência artificial aplicada a recursos humanos', 'posto_id' => 10],
    ['nome' => 'Metodologias de gestão do desempenho', 'posto_id' => 10],
    ['nome' => 'Metodologias ágeis aplicadas à gestão de pessoas', 'posto_id' => 10],
    ['nome' => 'Modalidades de trabalho', 'posto_id' => 10],
    ['nome' => 'Modelos mentais de resultados, metas e eficiência', 'posto_id' => 10],
    ['nome' => 'Pesquisas e indicadores em recursos humanos', 'posto_id' => 10],
    ['nome' => 'Práticas de acolhimento e mediação', 'posto_id' => 10],
    ['nome' => 'Recrutamento e seleção', 'posto_id' => 10],
    ['nome' => 'Tendências do futuro do trabalho', 'posto_id' => 10],
    ['nome' => 'Trilhas de aprendizagem', 'posto_id' => 10],
    ['nome' => 'Valorização e reconhecimento', 'posto_id' => 10],
    ['nome' => 'Acessibilidade web', 'posto_id' => 11],
    ['nome' => 'Análise biopsicossocial da deficiência', 'posto_id' => 11],
    ['nome' => 'Normas de acessibilidade urbanística e arquitetônica', 'posto_id' => 11],
    ['nome' => 'Normas e recursos para promoção da acessibilidade digital', 'posto_id' => 11],
    ['nome' => 'Avaliação de periódicos científicos especializados', 'posto_id' => 12],
    ['nome' => 'Classificação de documentos', 'posto_id' => 12],
    ['nome' => 'Conservação e restauração de documentos físicos', 'posto_id' => 12],
    ['nome' => 'Descrição documental e elaboração de arranjo', 'posto_id' => 12],
    ['nome' => 'Direitos autorais', 'posto_id' => 12],
    ['nome' => 'Diretrizes para serviços e profissionais de arquivo e aplicação da LGPD', 'posto_id' => 12],
    ['nome' => 'Elaboração de índice bibliográfico', 'posto_id' => 12],
    ['nome' => 'Gestão e conservação de documentos digitais', 'posto_id' => 12],
    ['nome' => 'Memória institucional', 'posto_id' => 12],
    ['nome' => 'Produção editorial de documentos institucionais', 'posto_id' => 12],
    ['nome' => 'Sistema Eletrônico de Informações com foco em gestão documental', 'posto_id' => 12],
    ['nome' => 'Tratamento de obras raras e coleções bibliográficas especiais', 'posto_id' => 12],
    ['nome' => 'Uso de metadados', 'posto_id' => 12],
    ['nome' => 'Autocad', 'posto_id' => 13],
    ['nome' => 'BIM Revit', 'posto_id' => 13],
    ['nome' => 'Gestão de projetos em BIM Revit', 'posto_id' => 13],
    ['nome' => 'Layouts e espaços físicos de trabalho', 'posto_id' => 13],
    ['nome' => 'Manutenção predial', 'posto_id' => 13],
    ['nome' => 'Orçamento de obras e', 'posto_id' => 13],
    ['nome' => 'Sistema nacional de preços e índices para a construção civil - SINAPI', 'posto_id' => 13],
    ['nome' => 'Ética e integridade no âmbito institucional', 'posto_id' => 14],
    ['nome' => 'Gestão da inovação com foco na estratégia', 'posto_id' => 14],
    ['nome' => 'Gestão da sustentabilidade', 'posto_id' => 14],
    ['nome' => 'Gestão de riscos com foco na estratégia', 'posto_id' => 14],
    ['nome' => 'Governança e gestão estratégica', 'posto_id' => 14],
    ['nome' => 'Metodologias e técnicas inovadoras', 'posto_id' => 14],
    ['nome' => 'Processo de inovação', 'posto_id' => 14],
    ['nome' => 'Administração financeira e orçamentária', 'posto_id' => 15],
    ['nome' => 'Declaração de débitos e créditos tributários federais', 'posto_id' => 15],
    ['nome' => 'Gerenciamento de banco de dados (Access) para área financeira', 'posto_id' => 15],
    ['nome' => 'Retenção tributária', 'posto_id' => 15],
    ['nome' => 'Sistema integrado de gestão orçamentária e financeira da Justiça do Trabalho - SIGEO', 'posto_id' => 15],
    ['nome' => 'Tesouro Gerencial', 'posto_id' => 15],
    ['nome' => 'Denúncia - Admissibilidade e proteção', 'posto_id' => 16],
    ['nome' => 'Lei geral de proteção de dados e', 'posto_id' => 16],
    ['nome' => 'Lei de acesso à informação aplicadas à ouvidoria', 'posto_id' => 16],
    ['nome' => 'Mediação e conciliação para Ouvidoria', 'posto_id' => 16],
    ['nome' => 'Ouvidoria e solução de problemas do usuário', 'posto_id' => 16],
    ['nome' => 'Ciência de dados', 'posto_id' => 17],
    ['nome' => 'Design de produtos e serviços', 'posto_id' => 17],
    ['nome' => 'Estatística', 'posto_id' => 17],
    ['nome' => 'Ferramentas de business inteligence', 'posto_id' => 17],
    ['nome' => 'Governança de dados', 'posto_id' => 17],
    ['nome' => 'Letramento de dados', 'posto_id' => 17],
    ['nome' => 'Pesquisa judiciária', 'posto_id' => 17],
    ['nome' => 'Armamento e tiro', 'posto_id' => 18],
    ['nome' => 'Condução veicular policial', 'posto_id' => 18],
    ['nome' => 'Controle de distúrbios civis', 'posto_id' => 18],
    ['nome' => 'Direitos humanos voltados para área policial', 'posto_id' => 18],
    ['nome' => 'Explosivos', 'posto_id' => 18],
    ['nome' => 'Gerenciamento de crises', 'posto_id' => 18],
    ['nome' => 'Inteligência e contrainteligência', 'posto_id' => 18],
    ['nome' => 'Primeiros socorros para área policial', 'posto_id' => 18],
    ['nome' => 'Reciclagem de segurança', 'posto_id' => 18],
    ['nome' => 'Segurança de autoridades', 'posto_id' => 18],
    ['nome' => 'Habilidades interpessoais no atendimento ao público para profissionais de saúde', 'posto_id' => 19],
    ['nome' => 'Legislação em saúde', 'posto_id' => 19],
    ['nome' => 'Perícia em saúde', 'posto_id' => 19],
    ['nome' => 'Prevenção em saúde', 'posto_id' => 19],
    ['nome' => 'Promoção da saúde', 'posto_id' => 19],
    ['nome' => 'Saúde mental', 'posto_id' => 19],
    ['nome' => 'Saúde ocupacional', 'posto_id' => 19],
    ['nome' => 'Trabalho em equipe de saúde multidisciplinar', 'posto_id' => 19],
    ['nome' => 'Abordagens de Design com foco em TI', 'posto_id' => 20],
    ['nome' => 'Administração de ativos de infraestrutura', 'posto_id' => 20],
    ['nome' => 'Administração de ativos de infraestrutura de telecomunicações', 'posto_id' => 20],
    ['nome' => 'Análise de requisitos', 'posto_id' => 20],
    ['nome' => 'Arquitetura da Informação (UX/UI)', 'posto_id' => 20],
    ['nome' => 'Arquitetura de software e frameworks', 'posto_id' => 20],
    ['nome' => 'Automação de infraestrutura', 'posto_id' => 20],
    ['nome' => 'Ciência de dados e Inteligência Artificial', 'posto_id' => 20],
    ['nome' => 'Contratações de tecnologia da informação', 'posto_id' => 20],
    ['nome' => 'Desenvolvimento em Nuvem', 'posto_id' => 20],
    ['nome' => 'Ferramentas de desenvolvimento de software', 'posto_id' => 20],
    ['nome' => 'Gerenciamento de serviços de TI', 'posto_id' => 20],
    ['nome' => 'Gestão de dados', 'posto_id' => 20],
    ['nome' => 'Gestão de endpoints', 'posto_id' => 20],
    ['nome' => 'Gestão de infraestrutura', 'posto_id' => 20],
    ['nome' => 'Gestão de portais web', 'posto_id' => 20],
    ['nome' => 'Gestão de software', 'posto_id' => 20],
    ['nome' => 'Governança de TI', 'posto_id' => 20],
    ['nome' => 'Infraestrutura em Nuvem', 'posto_id' => 20],
    ['nome' => 'Inovação com foco em TI', 'posto_id' => 20],
    ['nome' => 'Kanban', 'posto_id' => 20],
    ['nome' => 'Métodos ágeis em TI', 'posto_id' => 20],
    ['nome' => 'Monitoramento de infraestrutura', 'posto_id' => 20],
    ['nome' => 'Monitoramento de infraestrutura de telecomunicações', 'posto_id' => 20],
    ['nome' => 'Planejamento estratégico em TI', 'posto_id' => 20],
    ['nome' => 'Plataforma Digital do Poder Judiciário com foco em TI', 'posto_id' => 20],
    ['nome' => 'Qualidade de software', 'posto_id' => 20],
    ['nome' => 'Segurança cibernética com foco em TI', 'posto_id' => 20],
    ['nome' => 'Segurança da informação com foco em TI', 'posto_id' => 20],
    ['nome' => 'Segurança cibernética para ativos de infraestrutura', 'posto_id' => 20],
    ['nome' => 'Soluções de Tecnologia da Informação como Serviço (IAAS, PAAS, SAAS)', 'posto_id' => 20],
    ['nome' => 'Transformação Digital com foco em TI', 'posto_id' => 20],
    ['nome' => 'Virtualização de infraestrutura', 'posto_id' => 20],
    ['nome' => 'Cultura organizacional ', 'posto_id' => 21],
    ['nome' => 'Organização do trabalho ', 'posto_id' => 21],
    ['nome' => 'Ética e integridade ', 'posto_id' => 21],
    ['nome' => 'Concentração e foco', 'posto_id' => 21],
    ['nome' => 'Planejamento ', 'posto_id' => 21],
    ['nome' => 'Relacionamento interpessoal ', 'posto_id' => 21],
    ['nome' => 'Trabalho em equipe', 'posto_id' => 21],
    ['nome' => 'Inteligência emocional ', 'posto_id' => 21],
    ['nome' => 'Diversidade e inclusão ', 'posto_id' => 21],
    ['nome' => 'Sustentabilidade ', 'posto_id' => 21],
    ['nome' => 'Colaboração ', 'posto_id' => 21],
    ['nome' => 'Administração de conflitos ', 'posto_id' => 21],
    ['nome' => 'Prevenção ao assédio e combate à violência laboral', 'posto_id' => 21],
    ['nome' => 'Análise e tomada de decisões', 'posto_id' => 21],
    ['nome' => 'Proatividade', 'posto_id' => 21],
    ['nome' => 'Negociação', 'posto_id' => 21],
    ['nome' => 'Autogerenciamento do trabalho', 'posto_id' => 21],
    ['nome' => 'Visão sistêmica', 'posto_id' => 21],
    ['nome' => 'Inovação', 'posto_id' => 21],
    ['nome' => 'Ferramentas de gestão de processos de trabalho', 'posto_id' => 21],
    ['nome' => 'Ferramenta de Business Inteligence', 'posto_id' => 21],
    ['nome' => 'Gerência de Projetos', 'posto_id' => 21],
    ['nome' => ' Práticas e Métodos Ágeis', 'posto_id' => 21],
    ['nome' => 'Redação de Pareceres', 'posto_id' => 21],
    ['nome' => 'Redação Argumentativa', 'posto_id' => 21],
    ['nome' => 'Análise de Riscos', 'posto_id' => 21],
    ['nome' => 'Design Thinking', 'posto_id' => 21],
    ['nome' => 'Experiência do Usuário', 'posto_id' => 21],
    ['nome' => 'Análise de Dados Estatísticos e Indicadores', 'posto_id' => 21],
    ['nome' => 'Governança', 'posto_id' => 21],
    ['nome' => 'Técnicas de Apresentação', 'posto_id' => 21],
    ['nome' => 'Portal Web', 'posto_id' => 21],
    ['nome' => 'Ferramentas de Transformação Digital', 'posto_id' => 21],
    ['nome' => 'Redação Oficial', 'posto_id' => 21],
    ['nome' => 'Regime Jurídico dos Servidores Públicos', 'posto_id' => 21],
    ['nome' => 'Regime Próprio de Previdência Social', 'posto_id' => 21],
    ['nome' => 'Redação de Relatórios', 'posto_id' => 21],
    ['nome' => 'Acesso à Informação e Proteção de Dados', 'posto_id' => 21],
    ['nome' => 'Direito Administrativo Direito Constitucional', 'posto_id' => 21],
    ['nome' => 'Segurança Cibernética e da Informação ', 'posto_id' => 21],
    ['nome' => 'Acessibilidade de Documentos', 'posto_id' => 21],
    ['nome' => 'Transformação de Documentos', 'posto_id' => 21],
    ['nome' => 'Língua Brasileira de Sinais - Libras', 'posto_id' => 21],
    ['nome' => 'Linguagem Inclusiva, Neutra e Acessível', 'posto_id' => 21],
    ['nome' => 'Linguagem Simples', 'posto_id' => 21],
    ['nome' => 'Sistema Eletrônico de Informações', 'posto_id' => 21],
    ['nome' => 'Segurança Cibernética e da Informação', 'posto_id' => 21],
    ['nome' => 'Sistema de Gestão Orçamentária e Financeira ', 'posto_id' => 21],
    ['nome' => 'Prevenção a Incêndios e Abandono Emergências', 'posto_id' => 21],
    ['nome' => 'Ferramentas Informatizadas de Comunicação e Produção', 'posto_id' => 21],
    ['nome' => 'Técnicas de Comunicação', 'posto_id' => 21],
    ['nome' => 'Língua Portuguesa', 'posto_id' => 21],
];
