<?php

$funcoes = [
    ['nome' => 'CJ-1 - ASSESSOR B', 'gestor' => 0],
    ['nome' => 'CJ-1 - ASSESSOR-CHEFE', 'gestor' => 1],
    ['nome' => 'CJ-1 - ASSISTENTE JUDICIÁRIO', 'gestor' => 0],
    ['nome' => 'CJ-1 - CHEFE DE DIVISÃO', 'gestor' => 1],
    ['nome' => 'CJ-1 - CHEFE DE GABINETE', 'gestor' => 1],
    ['nome' => 'CJ-1 - PREGOEIRO', 'gestor' => 0],
    ['nome' => 'CJ-1 - PRESIDENTE DA CMPD', 'gestor' => 0],
    ['nome' => 'CJ-2 - ASSESSOR A', 'gestor' => 0],
    ['nome' => 'CJ-2 - ASSESSOR-CHEFE', 'gestor' => 1],
    ['nome' => 'CJ-2 - COORDENADOR', 'gestor' => 1],
    ['nome' => 'CJ-3 - ASSESSOR', 'gestor' => 0],
    ['nome' => 'CJ-3 - ASSESSOR DA PRESIDÊNCIA', 'gestor' => 0],
    ['nome' => 'CJ-3 - ASSESSOR DE MINISTRO', 'gestor' => 0],
    ['nome' => 'CJ-3 - ASSESSOR-CHEFE', 'gestor' => 1],
    ['nome' => 'CJ-3 - CHEFE DE GABINETE', 'gestor' => 1],
    ['nome' => 'CJ-3 - DIRETOR DE SECRETARIA', 'gestor' => 1],
    ['nome' => 'CJ-3 - SECRETÁRIO', 'gestor' => 1],
    ['nome' => 'CJ-4 - DIRETOR-GERAL', 'gestor' => 1],
    ['nome' => 'CJ-4 - SECRETÁRIO-GERAL DA PRESIDÊNCIA', 'gestor' => 1],
    ['nome' => 'CJ-4 - SECRETÁRIO-GERAL DE GESTÃO DE PROCESSOS', 'gestor' => 1],
    ['nome' => 'CJ-4 - SECRETÁRIO-GERAL JUDICIÁRIO', 'gestor' => 1],
    ['nome' => 'FC-2 - ASSISTENTE 2', 'gestor' => 0],
    ['nome' => 'FC-3 - ASSISTENTE 3', 'gestor' => 0],
    ['nome' => 'FC-4 - ASSISTENTE 4', 'gestor' => 0],
    ['nome' => 'FC-5 - ASSISTENTE 5', 'gestor' => 0],
    ['nome' => 'FC-5 - SUPERVISOR DE SEÇÃO', 'gestor' => 1],
    ['nome' => 'FC-6 - ASSISTENTE 6', 'gestor' => 0],
    ['nome' => 'FC-6 - CHEFE DE NÚCLEO', 'gestor' => 1],
];
