<?php

$lotacoes = [
    ['sigla' => 'ASDIN', 'nome' => 'Assessoria de Acessibilidade, Diversidade e Inclusão'],
    ['sigla' => 'AGTIC', 'nome' => 'Assessoria de Apoio à Governança e Gestão de Tecnologia da Informação e Comunicação'],
    ['sigla' => 'ASPRODEC', 'nome' => 'Assessoria de Promoção do Trabalho Decente e dos Direitos Humanos'],
    ['sigla' => 'ARTINOV', 'nome' => 'Assessoria de Relacionamento de Tecnologia e Inovação'],
    ['sigla' => 'ACEPRES', 'nome' => 'Assessoria do Cerimonial da Presidência'],
    ['sigla' => 'ASJUR', 'nome' => 'Assessoria Jurídica'],
    ['sigla' => 'ASPAR', 'nome' => 'Assessoria Parlamentar'],
    ['sigla' => 'ASTA', 'nome' => 'Assessoria Técnica e Administrativa'],
    ['sigla' => 'CAAD', 'nome' => 'Coordenadoria de Apoio Administrativo'],
    ['sigla' => 'CAUGE', 'nome' => 'Coordenadoria de Auditoria de Gestão Administrativa'],
    ['sigla' => 'CAUPE', 'nome' => 'Coordenadoria de Auditoria de Gestão de Pessoal e Benefícios'],
    ['sigla' => 'CCP', 'nome' => 'Coordenadoria de Cadastramento Processual'],
    ['sigla' => 'CCADP', 'nome' => 'Coordenadoria de Classificação, Autuação e Distribuição de Processos'],
    ['sigla' => 'CDEP', 'nome' => 'Coordenadoria de Desenvolvimento de Pessoas'],
    ['sigla' => 'CDS', 'nome' => 'Coordenadoria de Desenvolvimento de Sistemas'],
    ['sigla' => 'CDOC', 'nome' => 'Coordenadoria de Documentação'],
    ['sigla' => 'CEIM', 'nome' => 'Coordenadoria de Editoria e Imprensa'],
    ['sigla' => 'CESTAT', 'nome' => 'Coordenadoria de Estatística'],
    ['sigla' => 'CGEDM', 'nome' => 'Coordenadoria de Gestão Documental e Memória'],
    ['sigla' => 'CGFC', 'nome' => 'Coordenadoria de Gestão e Apoio à Fiscalização de Contratos'],
    ['sigla' => 'CIF', 'nome' => 'Coordenadoria de Informações Funcionais'],
    ['sigla' => 'CITEC', 'nome' => 'Coordenadoria de Infra-Estrutura Tecnológica'],
    ['sigla' => 'CJUR', 'nome' => 'Coordenadoria de Jurisprudência'],
    ['sigla' => 'CLEP', 'nome' => 'Coordenadoria de Legislação de Pessoal'],
    ['sigla' => 'CLCON', 'nome' => 'Coordenadoria de Licitações e Contratos'],
    ['sigla' => 'CMAP', 'nome' => 'Coordenadoria de Manutenção e Projetos'],
    ['sigla' => 'COFIN', 'nome' => 'Coordenadoria de Orçamento e Finanças'],
    ['sigla' => 'CPOL', 'nome' => 'Coordenadoria de Polícia Judicial'],
    ['sigla' => 'CPE', 'nome' => 'Coordenadoria de Processos Eletrônicos'],
    ['sigla' => 'CQUALI', 'nome' => 'Coordenadoria de Qualidade de Serviços de Tecnologia da Informação e Comunicação'],
    ['sigla' => 'CRTV', 'nome' => 'Coordenadoria de Rádio e TV'],
    ['sigla' => 'CSAC', 'nome' => 'Coordenadoria de Saúde Complementar'],
    ['sigla' => 'CSEC', 'nome' => 'Coordenadoria de Segurança Cibernética'],
    ['sigla' => 'CSESP', 'nome' => 'Coordenadoria de Serviços Especiais'],
    ['sigla' => 'CSUP', 'nome' => 'Coordenadoria de Suporte Técnico aos Usuários'],
    ['sigla' => 'CDOCM', 'nome' => 'CSJT - Coordenadoria de Gestão Documental e Memória'],
    ['sigla' => 'CGCO', 'nome' => 'CSJT - Coordenadoria de Governança de Contratações e de Obras'],
    ['sigla' => 'CGTIC', 'nome' => 'CSJT - Coordenadoria de Governança em Tecnologia da Informação e Comunicação'],
    ['sigla' => 'CSAN', 'nome' => 'CSJT - Coordenadoria de Sistemas Administrativos Nacionais'],
    ['sigla' => 'CTPJE', 'nome' => 'CSJT - Coordenadoria Técnica do Processo Judicial Eletrônico'],
    ['sigla' => 'SECAUDI', 'nome' => 'CSJT - Secretaria de Auditoria'],
    ['sigla' => 'SGPES', 'nome' => 'CSJT - Secretaria de Gestão de Pessoas do Conselho Superior da Justiça do Trabalho'],
    ['sigla' => 'SEGGEST', 'nome' => 'CSJT - Secretaria de Governança e Gestão Estratégica'],
    ['sigla' => 'SEOFI', 'nome' => 'CSJT - Secretaria de Orçamento e Finanças'],
    ['sigla' => 'SETIC', 'nome' => 'CSJT - Secretaria de Tecnologia da Informação e Comunicação'],
    ['sigla' => 'SECMAT', 'nome' => 'CSJT - Secretaria do Concurso Público Nacional Unificado para Ingresso na Carreira da Magistratura do Trabalho'],
    ['sigla' => 'SEJUR', 'nome' => 'CSJT - Secretaria Jurídica, Processual e de Apoio às Sessões'],
    ['sigla' => 'SGA', 'nome' => 'CSJT - Secretaria-Geral Adjunta do Conselho Superior da Justiça do Trabalho'],
    ['sigla' => 'SGRCSJT', 'nome' => 'CSJT - Secretaria-Geral do Conselho Superior da Justiça do Trabalho - SGRCSJT'],
    ['sigla' => 'DIBER', 'nome' => 'Divisão de Administração do Berçário'],
    ['sigla' => 'DART', 'nome' => 'Divisão de Apoio e Registros Taquigráficos'],
    ['sigla' => 'DCID', 'nome' => 'Divisão de Ciência de Dados'],
    ['sigla' => 'DCI', 'nome' => 'Divisão de Comunicação Institucional'],
    ['sigla' => 'DCVD', 'nome' => 'Divisão de Comunicação Visual e Design'],
    ['sigla' => 'DCONF', 'nome' => 'Divisão de Conformidade'],
    ['sigla' => 'DICONT', 'nome' => 'Divisão de Contabilidade'],
    ['sigla' => 'DSJUD', 'nome' => 'Divisão de Desenvolvimento de Sistemas Judiciais'],
    ['sigla' => 'DIEDUC', 'nome' => 'Divisão de Educação Corporativa'],
    ['sigla' => 'DIESIS', 'nome' => 'Divisão de Estratégia, Inovação e Sustentabilidade'],
    ['sigla' => 'DGEAD', 'nome' => 'Divisão de Gerenciamento de Aplicações e Dados'],
    ['sigla' => 'DINGER', 'nome' => 'Divisão de Integridade e de Gestão de Riscos'],
    ['sigla' => 'DIMAG', 'nome' => 'Divisão de Magistrados'],
    ['sigla' => 'DPJ', 'nome' => 'Divisão de Pesquisa Judiciária'],
    ['sigla' => 'DIPPP', 'nome' => 'Divisão de Preparação de Pagamento de Pessoal'],
    ['sigla' => 'DISAD', 'nome' => 'Divisão de Serviços Administrativos'],
    ['sigla' => 'DSGAB', 'nome' => 'Divisão de Suporte Especializado aos Gabinetes de Ministro'],
    ['sigla' => 'DIMEOD', 'nome' => 'Divisão Médica e Odontológica'],
    ['sigla' => 'CADM', 'nome' => 'ENAMAT - Coordenadoria Administrativa'],
    ['sigla' => 'CFOR', 'nome' => 'ENAMAT - Coordenadoria de Formação'],
    ['sigla' => 'CPESQ', 'nome' => 'ENAMAT - Coordenadoria de Pesquisa'],
    ['sigla' => 'DIRENAMAT', 'nome' => 'ENAMAT - Direção da Escola Nacional de Formação e Aperfeiçoamento de Magistrados do Trabalho'],
    ['sigla' => 'GCG', 'nome' => 'Gabinete da Corregedoria-Geral da Justiça do Trabalho'],
    ['sigla' => 'GMDMA', 'nome' => 'Gabinete da Ministra Delaíde Miranda Arantes'],
    ['sigla' => 'GMKA', 'nome' => 'Gabinete da Ministra Kátia Magalhães Arruda'],
    ['sigla' => 'GMLC', 'nome' => 'Gabinete da Ministra Liana Chaib'],
    ['sigla' => 'GMMCP', 'nome' => 'Gabinete da Ministra Maria Cristina Irigoyen Peduzzi'],
    ['sigla' => 'GMMHM', 'nome' => 'Gabinete da Ministra Maria Helena Mallmann'],
    ['sigla' => 'GMMAR', 'nome' => 'Gabinete da Ministra Morgana de Almeida Richa'],
    ['sigla' => 'GP', 'nome' => 'Gabinete da Presidência'],
    ['sigla' => 'GVP', 'nome' => 'Gabinete da Vice-Presidência'],
    ['sigla' => 'GDGSET', 'nome' => 'Gabinete do Diretor-Geral da Secretaria do Tribunal'],
    ['sigla' => 'GMABB', 'nome' => 'Gabinete do Ministro Alberto Bastos Balazeiro'],
    ['sigla' => 'GMAAB', 'nome' => 'Gabinete do Ministro Alexandre de Souza Agra Belmonte'],
    ['sigla' => 'GMALR', 'nome' => 'Gabinete do Ministro Alexandre Luiz Ramos'],
    ['sigla' => 'GMARPJ', 'nome' => 'Gabinete do Ministro Amaury Rodrigues Pinto Junior'],
    ['sigla' => 'GMFG', 'nome' => 'Gabinete do Ministro Antônio Fabrício de Matos Gonçalves'],
    ['sigla' => 'GMACC', 'nome' => 'Gabinete do Ministro Augusto César Leite de Carvalho'],
    ['sigla' => 'GMBM', 'nome' => 'Gabinete do Ministro Breno Medeiros'],
    ['sigla' => 'GMCMB', 'nome' => 'Gabinete do Ministro Cláudio Mascarenhas Brandão'],
    ['sigla' => 'GMDAR', 'nome' => 'Gabinete do Ministro Douglas Alencar Rodrigues'],
    ['sigla' => 'GMEV', 'nome' => 'Gabinete do Ministro Evandro Valadão'],
    ['sigla' => 'GMCB', 'nome' => 'Gabinete do Ministro Guilherme Augusto Caputo Bastos'],
    ['sigla' => 'GMHCS', 'nome' => 'Gabinete do Ministro Hugo Carlos Scheuermann'],
    ['sigla' => 'GMIGM', 'nome' => 'Gabinete do Ministro Ives Gandra da Silva Martins Filho'],
    ['sigla' => 'GMJRP', 'nome' => 'Gabinete do Ministro José Roberto Freire Pimenta'],
    ['sigla' => 'GMLS', 'nome' => 'Gabinete do Ministro Leonaldo Silva'],
    ['sigla' => 'GMDS', 'nome' => 'Gabinete do Ministro Luiz José Dezena da Silva'],
    ['sigla' => 'GMMGD', 'nome' => 'Gabinete do Ministro Maurício Godinho Delgado'],
    ['sigla' => 'GMNAD', 'nome' => 'Gabinete do Ministro Nelson Antônio Daiha'],
    ['sigla' => 'GMSPM', 'nome' => 'Gabinete do Ministro Sergio Pinto Martins'],
    ['sigla' => 'GMVMF', 'nome' => 'Gabinete do Ministro Vieira de Mello Filho'],
    ['sigla' => 'NCAD', 'nome' => 'Núcleo de Contratos e Apoio Administrativo'],
    ['sigla' => 'NEDS', 'nome' => 'Núcleo de Educação em Saúde'],
    ['sigla' => 'NINT', 'nome' => 'Núcleo de Inteligência'],
    ['sigla' => 'NLT', 'nome' => 'Núcleo de Logística de Transportes'],
    ['sigla' => 'NPOL', 'nome' => 'Núcleo de Policiamento Ostensivo'],
    ['sigla' => 'NDIC', 'nome' => 'Núcleo de Segurança de Dignitários e Capacitação'],
    ['sigla' => 'NUGEPSVP', 'nome' => 'NUGEP-SVP - Seção de Gerenciamento de Recursos Extraordinários Trabalhistas em Repercussão Geral'],
    ['sigla' => 'OUV', 'nome' => 'Ouvidoria'],
    ['sigla' => 'SETR1', 'nome' => 'Secretaria da 1ª Turma'],
    ['sigla' => 'SETR2', 'nome' => 'Secretaria da 2ª Turma'],
    ['sigla' => 'SETR3', 'nome' => 'Secretaria da 3ª Turma'],
    ['sigla' => 'SETR4', 'nome' => 'Secretaria da 4ª Turma'],
    ['sigla' => 'SETR5', 'nome' => 'Secretaria da 5ª Turma'],
    ['sigla' => 'SETR6', 'nome' => 'Secretaria da 6ª Turma'],
    ['sigla' => 'SETR7', 'nome' => 'Secretaria da 7ª Turma'],
    ['sigla' => 'SETR8', 'nome' => 'Secretaria da 8ª Turma'],
    ['sigla' => 'SECG', 'nome' => 'Secretaria da Corregedoria-Geral da Justiça do Trabalho'],
    ['sigla' => 'SESDI1', 'nome' => 'Secretaria da Subseção I Especializada em Dissídios Individuais'],
    ['sigla' => 'SESDI2', 'nome' => 'Secretaria da Subseção II Especializada em Dissídios Individuais'],
    ['sigla' => 'SEGVP', 'nome' => 'Secretaria da Vice-Presidência'],
    ['sigla' => 'SEA', 'nome' => 'Secretaria de Administração'],
    ['sigla' => 'SEAUD', 'nome' => 'Secretaria de Auditoria'],
    ['sigla' => 'SECOM', 'nome' => 'Secretaria de Comunicação Social'],
    ['sigla' => 'SEGPES', 'nome' => 'Secretaria de Gestão de Pessoas'],
    ['sigla' => 'SPR', 'nome' => 'Secretaria de Gestão de Precedentes'],
    ['sigla' => 'SEPJD', 'nome' => 'Secretaria de Pesquisa Judiciária e Ciência de Dados'],
    ['sigla' => 'SEPREX', 'nome' => 'Secretaria de Processamento de Recursos Extraordinários'],
    ['sigla' => 'SESAUD', 'nome' => 'Secretaria de Saúde'],
    ['sigla' => 'SES', 'nome' => 'Secretaria de Segurança'],
    ['sigla' => 'SETIN', 'nome' => 'Secretaria de Tecnologia da Informação e Comunicação'],
    ['sigla' => 'SETPOESDC', 'nome' => 'Secretaria do Tribunal Pleno, do Órgão Especial e da Seção Especializada em Dissídios Coletivos'],
    ['sigla' => 'SEGP', 'nome' => 'Secretaria-Geral do Gabinete da Presidência'],
    ['sigla' => 'SEGJUD', 'nome' => 'Secretaria-Geral Judiciária'],
    ['sigla' => 'SEGGE', 'nome' => 'SEGGE - Secretaria de Gorvenança e de Gestão Estratégica'],
    ['sigla' => 'AITEC', 'nome' => 'Assessoria de Apoio e Inovação Tecnológica'],
    ['sigla' => 'CMPD', 'nome' => 'Comissão Permanente Disciplinar'],
    ['sigla' => 'CDEPLP', 'nome' => 'Coordenadoria de Desenvolvimento de Pessoas (Provisória)'],
    ['sigla' => 'CGDIGITAL', 'nome' => 'Coordenadoria de Governança e Evolução Digital'],
    ['sigla' => 'CSJT', 'nome' => 'CSJT - Conselho Superior da Justiça do Trabalho'],
    ['sigla' => 'DIEX', 'nome' => 'Divisão de Informação e Experiência do Usuário'],
    ['sigla' => 'SENAMAT', 'nome' => 'ENAMAT - Secretaria Executiva da Escola Nacional de Formação e Aperfeiçoamento de Magistrados do Trabalho'],
    ['sigla' => 'ENAMAT', 'nome' => 'Escola Nacional de Formação da Magistratura do Trabalho'],
    ['sigla' => 'GMDMC', 'nome' => 'Gabinete da Ministra Dora Maria da Costa'],
    ['sigla' => 'GDCJPC', 'nome' => 'Gabinete do Desembargador Convocado José Pedro de Camargo Rodrigues de Souza'],
    ['sigla' => 'GDCMP', 'nome' => 'Gabinete do Desembargador Convocado Marcelo Lamego Pertence'],
    ['sigla' => 'GMLBC', 'nome' => 'Gabinete do Ministro Lelio Bentes Corrêa'],
    ['sigla' => 'SEAR', 'nome' => 'Secretaria de Admissibilidade de Recursos'],
    ['sigla' => 'SEGGEPRO', 'nome' => 'Secretaria-Geral de Gestão de Processos'],
];
